package com.pineypiney.game_engine.resources.textures.parameters

import org.lwjgl.opengl.GL11C
import org.lwjgl.vulkan.VK10

enum class TextureFilter(val opengl: Int, val vulkanImage: Int, val vulkanMipmap: Int) {
	LINEAR(GL11C.GL_LINEAR, VK10.VK_FILTER_LINEAR, -1),
	NEAREST(GL11C.GL_NEAREST, VK10.VK_FILTER_NEAREST, -1),
	LINEAR_LINEAR(GL11C.GL_LINEAR_MIPMAP_LINEAR, VK10.VK_FILTER_LINEAR, VK10.VK_SAMPLER_MIPMAP_MODE_LINEAR),
	NEAREST_LINEAR(GL11C.GL_NEAREST_MIPMAP_LINEAR, VK10.VK_FILTER_NEAREST, VK10.VK_SAMPLER_MIPMAP_MODE_LINEAR),
	LINEAR_NEAREST(GL11C.GL_LINEAR_MIPMAP_NEAREST, VK10.VK_FILTER_LINEAR, VK10.VK_SAMPLER_MIPMAP_MODE_NEAREST),
	NEAREST_NEAREST(GL11C.GL_NEAREST_MIPMAP_NEAREST, VK10.VK_FILTER_NEAREST, VK10.VK_SAMPLER_MIPMAP_MODE_NEAREST)
}