package com.pineypiney.game_engine.resources.textures

import org.lwjgl.opengl.GL43C.*

// https://gist.github.com/Kos/4739337
enum class TextureFormat(val id: Int, val base: Int, val dataType: Int) {

	RED(GL_RED, GL_RED, GL_UNSIGNED_BYTE),
	R8(GL_R8, GL_RED, GL_UNSIGNED_BYTE),
	R16(GL_R16, GL_RED, GL_UNSIGNED_SHORT),
	R16F(GL_R16F, GL_RED, GL_HALF_FLOAT),
	R32F(GL_R32F, GL_RED, GL_FLOAT),

	R8I(GL_R8I, GL_RED_INTEGER, GL_INT),
	R16I(GL_R16I, GL_RED_INTEGER, GL_INT),
	R32I(GL_R32I, GL_RED_INTEGER, GL_INT),
	R8UI(GL_R8UI, GL_RED_INTEGER, GL_UNSIGNED_INT),
	R16UI(GL_R16UI, GL_RED_INTEGER, GL_UNSIGNED_INT),
	R32UI(GL_R32UI, GL_RED_INTEGER, GL_UNSIGNED_INT),


	RG(GL_RG, GL_RG, GL_UNSIGNED_BYTE),
	RG8(GL_RG8, GL_RG, GL_UNSIGNED_BYTE),
	RG16(GL_RG16, GL_RG, GL_UNSIGNED_SHORT),
	RG16F(GL_R16F, GL_RG, GL_HALF_FLOAT),
	RG32F(GL_R32F, GL_RG, GL_FLOAT),

	RG8I(GL_RG8I, GL_RG_INTEGER, GL_INT),
	RG16I(GL_RG16I, GL_RG_INTEGER, GL_INT),
	RG32I(GL_RG32I, GL_RG_INTEGER, GL_INT),
	RG8UI(GL_RG8UI, GL_RG_INTEGER, GL_UNSIGNED_INT),
	RG16UI(GL_RG16UI, GL_RG_INTEGER, GL_UNSIGNED_INT),
	RG32UI(GL_RG32UI, GL_RG_INTEGER, GL_UNSIGNED_INT),


	RGB(GL_RGB, GL_RGB, GL_UNSIGNED_BYTE),
	RGB8(GL_RGB8, GL_RGB, GL_UNSIGNED_BYTE),
	RGB16(GL_RGB16, GL_RGB, GL_UNSIGNED_SHORT),
	RGB16F(GL_RGB16F, GL_RGB, GL_HALF_FLOAT),
	RGB32F(GL_RGB32F, GL_RGB, GL_FLOAT),

	RGB8I(GL_RGB8I, GL_RGB_INTEGER, GL_INT),
	RGB16I(GL_RGB16I, GL_RGB_INTEGER, GL_INT),
	RGB32I(GL_RGB32I, GL_RGB_INTEGER, GL_INT),
	RGB8UI(GL_RGB8UI, GL_RGB_INTEGER, GL_UNSIGNED_INT),
	RGB16UI(GL_RGB16UI, GL_RGB_INTEGER, GL_UNSIGNED_INT),
	RGB32UI(GL_RGB32UI, GL_RGB_INTEGER, GL_UNSIGNED_INT),

	R3_G3_B2(GL_R3_G3_B2, GL_RGB, GL_UNSIGNED_BYTE_3_3_2),


	RGBA(GL_RGBA, GL_RGBA, GL_UNSIGNED_BYTE),
	RGBA8(GL_RGBA8, GL_RGBA, GL_UNSIGNED_BYTE),
	RGBA12(GL_RGBA12, GL_RGBA, GL_UNSIGNED_SHORT),
	RGBA16(GL_RGBA16, GL_RGBA, GL_UNSIGNED_SHORT),
	RGBA16F(GL_RGBA16F, GL_RGBA, GL_HALF_FLOAT),
	RGBA32F(GL_RGBA32F, GL_RGBA, GL_FLOAT),

	RGBA8I(GL_RGBA8I, GL_RGBA_INTEGER, GL_INT),
	RGBA16I(GL_RGBA16I, GL_RGBA_INTEGER, GL_INT),
	RGBA32I(GL_RGBA32I, GL_RGBA_INTEGER, GL_INT),
	RGBA8UI(GL_RGBA8UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT),
	RGBA16UI(GL_RGBA16UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT),
	RGBA32UI(GL_RGBA32UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT),

	RGB5_A1(GL_RGB5_A1, GL_RGBA, GL_UNSIGNED_SHORT_5_5_5_1),
	RGBA4(GL_RGBA4, GL_RGBA, GL_UNSIGNED_SHORT_4_4_4_4),
	RGBA2(GL_RGBA2, GL_RGBA, GL_UNSIGNED_SHORT_4_4_4_4),
	RGB10A2(GL_RGB10_A2, GL_RGBA, GL_UNSIGNED_INT_10_10_10_2),
	RGB10A2UI(GL_RGB10_A2UI, GL_RGBA_INTEGER, GL_UNSIGNED_INT_10_10_10_2),


	DEPTH16(GL_DEPTH_COMPONENT16, GL_DEPTH_COMPONENT, GL_UNSIGNED_SHORT),
	DEPTH24(GL_DEPTH_COMPONENT24, GL_DEPTH_COMPONENT, GL_UNSIGNED_INT),
	DEPTH32(GL_DEPTH_COMPONENT32, GL_DEPTH_COMPONENT, GL_UNSIGNED_INT),
	DEPTH32F(GL_DEPTH_COMPONENT32F, GL_DEPTH_COMPONENT, GL_FLOAT),

	DEPTH24_STENCIL8(GL_DEPTH24_STENCIL8, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8),
	DEPTH32F_STENCIL8(GL_DEPTH32F_STENCIL8, GL_DEPTH_STENCIL, GL_FLOAT_32_UNSIGNED_INT_24_8_REV);


	companion object {
		fun fromGlConst(value: Int): TextureFormat? {
			return TextureFormat.entries.firstOrNull { it.id == value }
		}
	}

	enum class Channels(val id: Int, val size: Int){
		R(GL_RED, 1),
		R_INT(GL_RED_INTEGER, 1),
		RG(GL_RED, 2),
		RG_INT(GL_RED_INTEGER, 2),
		RGB(GL_RED, 3),
		RGB_INT(GL_RED_INTEGER, 3),
		RGBA(GL_RED, 4),
		RGBA_INT(GL_RED_INTEGER, 4),
		DEPTH(GL_DEPTH_COMPONENT, 1),
		DEPTH_STENCIL(GL_DEPTH_STENCIL, 2),
	}
}