package com.pineypiney.game_engine.resources.shaders.parameters

import com.pineypiney.game_engine.util.ApiEnum
import org.lwjgl.opengl.GL11C
import org.lwjgl.vulkan.VK10

enum class Blending(override val opengl: Int, override val vulkan: Int) : ApiEnum {
	ZERO(GL11C.GL_ZERO, VK10.VK_BLEND_FACTOR_ZERO),
	ONE(GL11C.GL_ONE, VK10.VK_BLEND_FACTOR_ONE),
	SRC_COLOR(GL11C.GL_SRC_COLOR, VK10.VK_BLEND_FACTOR_SRC_COLOR),
	ONE_MINUS_SRC_COLOR(GL11C.GL_ONE_MINUS_SRC_COLOR, VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR),
	SRC_ALPHA(GL11C.GL_SRC_ALPHA, VK10.VK_BLEND_FACTOR_SRC_ALPHA),
	ONE_MINUS_SRC_ALPHA(GL11C.GL_ONE_MINUS_SRC_ALPHA, VK10.VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA),
	DST_COLOR(GL11C.GL_DST_COLOR, VK10.VK_BLEND_FACTOR_DST_COLOR),
	ONE_MINUS_DST_COLOR(GL11C.GL_ONE_MINUS_DST_COLOR, VK10.VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR),
	DST_ALPHA(GL11C.GL_DST_ALPHA, VK10.VK_BLEND_FACTOR_DST_ALPHA),
	ONE_MINUS_DST_ALPHA(GL11C.GL_ONE_MINUS_DST_ALPHA, VK10.VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA),
}