package com.pineypiney.game_engine.resources.shaders.parameters

import com.pineypiney.game_engine.util.ApiEnum
import org.lwjgl.opengl.GL11C
import org.lwjgl.vulkan.VK10

enum class InputTopology(override val opengl: Int, override val vulkan: Int) : ApiEnum {
	POINTS(GL11C.GL_POINTS, VK10.VK_PRIMITIVE_TOPOLOGY_POINT_LIST),
	LINES(GL11C.GL_LINES, VK10.VK_PRIMITIVE_TOPOLOGY_LINE_LIST),
	LINE_LOOP(GL11C.GL_LINE_LOOP, 0),
	LINE_STRIP(GL11C.GL_LINE_STRIP, VK10.VK_PRIMITIVE_TOPOLOGY_LINE_STRIP),
	TRIANGLES(GL11C.GL_TRIANGLES, VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST),
	TRIANGLE_STRIP(GL11C.GL_TRIANGLE_STRIP, VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP),
	TRIANGLE_FAN(GL11C.GL_TRIANGLE_FAN, VK10.VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN),
}