package com.pineypiney.game_engine.resources.shaders

import org.lwjgl.opengl.GL43C
import org.lwjgl.vulkan.VK10

enum class ShaderStage(val opengl: Int, val vulkan: Int) {
	VERTEX(GL43C.GL_VERTEX_SHADER, VK10.VK_SHADER_STAGE_VERTEX_BIT),
	FRAGMENT(GL43C.GL_FRAGMENT_SHADER, VK10.VK_SHADER_STAGE_FRAGMENT_BIT),
	TESS_CTRL(GL43C.GL_TESS_CONTROL_SHADER, VK10.VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT),
	TESS_EVAL(GL43C.GL_TESS_EVALUATION_SHADER, VK10.VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT),
	GEOMETRY(GL43C.GL_GEOMETRY_SHADER, VK10.VK_SHADER_STAGE_GEOMETRY_BIT),
	COMPUTE(GL43C.GL_COMPUTE_SHADER, VK10.VK_SHADER_STAGE_COMPUTE_BIT)
}